---
- name: Run docker container
  hosts: jenkinsNodeVM
  gather_facts: false
  remote_user: vagrant

  tasks:
    - name: Install pip
      apt:
        update_cache: yes
        name:
          - python3-pip

    - name: Install pexpect
      pip:
        name: pexpect
      
    - name: Install python docker module
      pip:
        name: docker

    - name: Run Docker container 
      docker_container:
        name: demo
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        recreate: yes
        detach: true
        ports:
          - "80:5000"
